[Scia Reto](https://sciareto.org) mind map   
> __version__=`1.1`,showJumps=`true`
---

# 命令合集
> align=`left`


## Scrapy常用命令

### Available commands :<br/>  bench      Run quick benchmark test \#测试电脑性能<br/>  fetch      Fetch a URL using the scrapy down1oader\#将源代码下载下来并显示出来<br/>  genspider      Generate new spider using pre\-defined temp1ates\#创建一个新的spider文件<br/>  runspider      Run a self\-contained spider \(without creating a project\)\# 这个和通过craw1启动爬虫不同，scrapy runspider爬虫文件名称<br/>  settings      Get settings values\#获取当前的配置信息<br/>  she11      Interactive scraping console\#进入scrapy 的交互模式<br/>  startproject      create new project\#创建爬虫项目<br/>  version      Print scrapy version\#显示scrapy框架的版本<br/>  view      open URL in browser，as seen by scrapy\#将网页document内容下载下来，并且在浏览器显示出来
> align=`left`


## miniconda命令合集
> leftSide=`true`


### 查看当前存在的虚拟环境

#### conda env list

### 创建虚拟环境

#### conda create \-n 环境名 python=x\.x

### 激活指定虚拟环境\(就是选择当前环境的python\)

#### activate 环境名

### 退出虚拟环境

#### deactivate   退出

### 删除环境

#### conda remove \-n 环境名 \-\-all
